apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      nodeSelector:
        pool: warm
      tolerations:
        - key: "warm-pool"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: worker
          image: kartikeya532001/llm-worker:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis.app.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: regcred
