name: Infra Deploy (Terraform)

on:
  push:
    branches: [ master ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ master ]
    paths: 
      - "infra/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout code
      # -------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # Setup Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # -------------------------
      # Configure AWS Credentials
      # -------------------------
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # -------------------------
      # Terraform clean
      # -------------------------
      - name: Terraform clean
        run: rm -rf .terraform .terraform.lock.hcl
        working-directory: infra/terraform

      # -------------------------
      # Terraform Init
      # -------------------------
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: infra/terraform

      # -------------------------
      # Terraform Validate
      # -------------------------
      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/terraform

      # -------------------------
      # Terraform Plan (Optional Check)
      # -------------------------
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infra/terraform

      # -------------------------
      # Terraform Apply
      # -------------------------
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra/terraform

      # -------------------------
      # Export EKS SSH Key
      # -------------------------
      - name: Export EKS SSH Key
        run: |
          # Check if output exists
          if terraform output -json | jq -e '.eks_private_key_pem.value' >/dev/null; then
            terraform output -raw eks_private_key_pem > llm-eks-key.pem
            chmod 400 llm-eks-key.pem
          else
            echo "Warning: eks_private_key_pem output not found."
          fi
        working-directory: infra/terraform

      # -------------------------
      # Upload SSH Key Artifact
      # -------------------------
      - name: Upload SSH Key Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llm-eks-key
          path: infra/terraform/llm-eks-key.pem