name: Infra Deploy (Terraform)

on:
  push:
    branches: [ master ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ master ]
    paths: 
      - "infra/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Terraform clean
        run: rm -rf .terraform .terraform.lock.hcl
        working-directory: infra/terraform

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: infra/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/terraform

      - name: Terraform Plan
        run: |
          export TF_LOG=DEBUG
          terraform plan -out=tfplan | tee plan.log
        working-directory: infra/terraform

      - name: Upload Terraform Plan Log
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-log
          path: infra/terraform/plan.log

      - name: Terraform Apply
        run: |
          export TF_LOG=DEBUG
          terraform apply -auto-approve tfplan | tee apply.log
        working-directory: infra/terraform

      - name: Upload Terraform Apply Log
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-log
          path: infra/terraform/apply.log

      # -----------------------------------
      # Extract EKS SSH Private Key
      # -----------------------------------
      - name: Export EKS SSH Key
        run: |
          terraform output -raw eks_private_key_pem > llm-eks-key.pem
          chmod 400 llm-eks-key.pem
        working-directory: infra/terraform

      - name: Upload SSH Key Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llm-eks-key
          path: infra/terraform/llm-eks-key.pem
